options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "northamerica-south1-docker.pkg.dev/microservicios-456418/image-regis/auth-ms",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "northamerica-south1-docker.pkg.dev/microservicios-456418/image-regis/auth-ms",
      ]